gems:
  - jemoji
  - jekyll-sitemap
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: fs
description: fuad saud's worhtless thougts
url: //fuad.im
repo_url: //github.com/fuadsaud/fuadsaud.github.io
avatar: //www.gravatar.com/avatar/a6ac07e8e5efbba8bec17c104c8e4bb8.png?s=150
author:
  name: Fuad Saud
  email: fuadfsaud@gmail.com
  location: Rochester, NY
  links:
    github: //github.com/fuadsaud
    linkedin: //www.linkedin.com/in/fuadsaud/
    socareers: //careers.stackoverflow.com/fuad
    twitter: //twitter.com/fuadsaud
