pygments: true
markdown: redcarpet
permalink: /:year/:month/:day/:title.html
name: fs
description: Thoughts of a dying rubyist
url: http://fuadsaud.github.io
author:
  name: Fuad Saud
  email: fuadksd@gmail.com
