gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
permalink: /:year/:month/:day/:title
sass:
  sass_dir: bower_components/
name: fs
description: fuad saud's worhtless thougts
url: //fuad.im
repo_url: //github.com/fuadsaud/fuadsaud.github.io
feed_url: /atom.xml
avatar: //www.gravatar.com/avatar/a6ac07e8e5efbba8bec17c104c8e4bb8.png?s=400
author:
  name: Fuad Saud
  email: fuadfsaud@gmail.com
  location: São Leopoldo, Brazil
  links:
    github: //github.com/fuadsaud
    linkedin: //www.linkedin.com/in/fuadsaud/
    socareers: //careers.stackoverflow.com/fuad
    stackexchange: //stackexchange.com/users/1280082/fuad-saud?tab=accounts
    twitter: //twitter.com/fuadsaud
feed:
  path: atom.xml
