gems:
  - jemoji
  - jekyll-sitemap
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: fs
description: fuad saud's worhtless thougts
url: http://fuadsaud.github.io
avatar: //www.gravatar.com/avatar/a6ac07e8e5efbba8bec17c104c8e4bb8.png?s=150
author:
  name: Fuad Saud
  email: fuadsaud@gmail.com
