gems:
  - jemoji
  - jekyll-sitemap
pygments: true
markdown: redcarpet
permalink: /:year/:month/:day/:title.html
name: fs
description: fuad saud's worhtless thougts
url: http://fuadsaud.github.io
author:
  name: Fuad Saud
  email: fuadsaud@icloud.com
